### ISSUE TITLE
Python federate ends with uncaught exception

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS-src#135]
Following the python test steps from `swig/python/README.md` the SENDER federate (only) runs fully but then errors out with:

```
PI SENDER: Broker disconnected
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```
Tested with:
`develop`  at ff2cc190fb16e2850a04468f1fb90d52d1541cf8
Anaconda python 3.6
Other dependencies (zmq, boost, cmake, etc.) installed via `brew`

**Comment by bpalmintier** [comment]
Maybe related to #134

**Comment by bpalmintier** [comment]
(Not related to #134) 
Correction: this only happens if using the external `helics_broker` call rather than the one that `pisender.py` sets up. Presumably the sender does not check if its broker got created and then later tries to stop it even if not started.

Full listing if `helics_broker 2` already running:
```
$ python pisender.py
PI SENDER: Helics version = 1.0.0.alpha (01-18-18)
Creating Broker
binding error on reply socket sleeping then will try again 
zmqError binding rep port tcp://127.0.0.1:23404Address already in use
Created Broker
Checking if Broker is connected
Checked if Broker is connected
PI SENDER: Value federate created
PI SENDER: Publication registered
PI SENDER: Entering execution mode
PI SENDER: Sending value pi = 3.142857142857143 at time 5.0 to PI RECEIVER
PI SENDER: Sending value pi = 3.142857142857143 at time 6.0 to PI RECEIVER
PI SENDER: Sending value pi = 3.142857142857143 at time 7.0 to PI RECEIVER
PI SENDER: Sending value pi = 3.142857142857143 at time 8.0 to PI RECEIVER
PI SENDER: Sending value pi = 3.142857142857143 at time 9.0 to PI RECEIVER
PI SENDER: Federate finalized
PI SENDER: Broker disconnected
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```

**Comment by bpalmintier** [comment]
Note: as of cf5c49dffc4e357adb06886c92fdb4d2a6f175b1 the swig/python directions no longer use `helics_broker` so this is not normally seen.

**Comment by kdheepak** [comment]
I'm adding @phlptp to the conversation as well, I've seen this too.

**Comment by phlptp** [comment]
My guess is that it is a similar root cause but different symptom than #134.  The real issue which I am struggling to deal with is that when it terminates different operating systems do different things with the threads.  I haven't seen this issue on Windows which is the platform I usually work on.  On linux in some cases it shows up something like #134.  On Mac it does something different.  

the problem as best as I can tell is this.  
A program finishes
the operating system goes into its cleanup execution which includes forcefully terminating threads
this prevents the threads from terminating gracefully which in most cases they are in the process of doing.  
the main thread is usually last but it is waiting on signals to know it can properly close, those signals never come and in some cases objects it has been using are destroyed already.  

the near term fix is to make sure the cleanUpHelicsLibrary() function is called last. or some additional delay is available before you exit the main function.    
the longer term fix is a rethinking of how the closeout is handled, but that is going to take some time

**Comment by phlptp** [comment]
@kdheepak can you check if this still occurs with the latest develop branch?

**Comment by kdheepak** [comment]
I can confirm that this is not longer an issue. I tested on build from commit cabc611.

![screen shot 2018-02-07 at 12 46 05 pm](https://user-images.githubusercontent.com/1813121/35937963-04cc0fe8-0c05-11e8-8bcd-2b0fba4e2066.png)
