### ISSUE TITLE
Swig and appveyor

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#199]
There appears to be something wrong with SWIG on Appveyor, none of the recent builds have passed due to a SWIG error.

I also noticed that we are a couple releases behind on which version of swig is being downloaded.  
Is there anything that can be done or is this a website failure?

**Comment by nightlark** [comment]
The chocolatey install command for swig is failing -- from the log it looks like it is downloading an html page instead of a zip file from sourceforge.

The most recent version of the swig package on chocolatey is 3.0.9, and that was added this past June. Discussion ~5 months ago by the current project maintainer is that an update to 3.0.12 is ready, but that the review process is really slow, and chocolatey keeps making the review process stricter.

**Comment by phlptp** [comment]
This seems to have resolved itself as the builds are getting past that point for the most part now.
