### ISSUE TITLE
Add HELICS to Cmake package registry on Windows

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-src#289]
https://cmake.org/cmake/help/v3.4/manual/cmake-packages.7.html#user-package-registry

Installer on Windows could add HELICS to the user package registry to tell cmake where to search for the HELICS install.

**Comment by phlptp** [comment]
This is going to require some additional investigation, moving to 1.3

**Comment by phlptp** [comment]
I was running into some comments from the CMAKE maintainers that using the package registry on windows was being discouraged due to the practical considerations of stale entries.  

It looks like to actually do this we would need to customize the NSIS template and make sure the uninstall does the same thing.  
I am wondering if better integration with package managers might be a better long term solution thank tinkering with the registry in windows.  

I added an option in the windows installer to add HELICS to the System path.  I will be modifying an addHELICS.cmake to be able to pick it up from there if the HELICS binary is on the path.  

The question is do we still want to pursue adding a registry entry?

**Comment by phlptp** [comment]
@nightlark do you think this is still something we want to do?  It seems that capability is being discouraged.

**Comment by nightlark** [comment]
It seems like manually setting paths to dependencies on Windows is common, and it removes ambiguity if you have multiple versions of HELICS on a system.

**Comment by phlptp** [comment]
I am going to close this issue then,  We can make a new one or reopen if it is later determined to be necessary.
