### ISSUE TITLE
"Zmq port already in use" for a large number of federates started as separate processes

### ISSUE THREAD

**Issue by MuMonish** [GMLC-TDC/HELICS-src#392]
For a larger number of federates (400 plus) started within a single system, occasionally there is an error on zmq socket in use --->
"binding error on reply socket sleeping then will try again
zmqError binding rep port tcp://127.0.0.1:23404Address already in use"
Federate language binding --> python (executed with runner/shell script and error occurred for 380th federates). 
Some unusual that happened during configuration in linux which might be of interest ---> (Looking for pthread_create - not found)

Code used for generating the runner and python federates--->
https://gist.github.com/MuMonish/d78d12da89feb05474aa28d940a1292b

**Comment by phlptp** [comment]
this will happen occasionally if the previous broker has not shutdown completely, and that can take a little while for large runs.  Issue #296 is related.  

I know the port allocation system is not the most robust thing right now.  It probably should be refactored now that we are getting to 400+ federate tests with ZMQ.

**Comment by phlptp** [comment]
The remedy for this issue is improving the port allocation system and adding some logic in the zmq communicator to detect this situation and request ports again.    This is a bit bigger task and probably won't be done by the end of the month with the rest of the 1.3 stuff.

**Comment by trevorhardy** [comment]
Is this something that we can put Shwetha (@shwethanidd) on? The core of our scalability testing has federation size as a significant factor and we have that webinar we're giving in a handful of weeks.

**Comment by phlptp** [comment]
certainly,  would welcome help.

**Comment by shwethanidd** [comment]
@phlptp: I have been re looking at this problem since a couple of days. If I look at findOpenPorts() in src/helics/core/zmq/ZmqComss.cpp, the ports are assigned in a sequential manner without verifying if the assigned port is being used or not. Instead, my thought was to assign the port non-sequentially by asking OS kernel to give an unused port. 
Pseudo code:
1. Create a new ZMQ socket 'sock', set socket property flag, ZMQ_LINGER = 0
2. sock.bind('local', 0) # Bind to OS assigned port
3. addr, port = s.getsockname() # This gives unused port
4. sock.close()

Let me know if this sounds good. I'll be testing this today.

**Comment by phlptp** [comment]
I have modified this somewhat in the HELICS_2_0 branch, so you might want to check that out.    We will also need to make sure this works for all networking cores, whatever solution is developed since the tcp and udp cores have a similar issue.    One issue with getting a port from the OS is predictability.  This will typically be a high number port, and a broker on another machine has to be able to connect to it, that means the firewall needs an opening for that specific port.   with the previous range this was more feasible.     Maybe we want to have this as an option on ZMQ comms though.  I will be interested in how well this works.

**Comment by nightlark** [comment]
Between machines in a cluster, I don't think firewalls are much of an issue -- connections between two machines with a firewall between them seems like a situation where you'd want to specify what port they are connecting to each other with.

**Comment by shwethanidd** [comment]
Yes, I like the idea of adding an option in ZMQComms to use static port allocation or dynamic port allocation. And user can choose one or the other type based on firewall.
