### ISSUE TITLE
Update C interface to make it more consistent

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#42]

**Comment by kdheepak** [comment]
Function naming convention for C interface:

**Option 1**

```c 
helics_{modulename}_{action}[_{subject}] ( ... ) {
    ...
}
```

e.g. 

```c
helicsStatus helics_federateinfo_setfederatename (helics_federate_info_t fi, const char *name);
helicsStatus helics_federateinfo_setcorename (helics_federate_info_t fi, const char *corename);
helicsStatus helics_federateinfo_setcoreinitstring (helics_federate_info_t fi, const char *coreInit);
```

Here, `federateinfo` is the module name.

Optionally, we could have underscore separators for all words.

e.g.

```c
helicsStatus helics_federate_info_set_federate_name (helics_federate_info_t fi, const char *name);
helicsStatus helics_federate_info_set_core_name (helics_federate_info_t fi, const char *corename);
helicsStatus helics_federate_info_set_core_init_string (helics_federate_info_t fi, const char *coreInit);
```

Question: What to do about the following function? It does not have a clear module name.

```c
helics_core helics_create_core (const char *type, const char *name, const char *initString);
```

The advantage of this option is that is enables easier autocompletion in IDEs to find what a user is looking for.

The disadvantage of including the module names is that the names may have redundant information.

```c
helics_message_federate helics_messagefederate_createmessagefederate (const helics_federate_info_t fi);
helics_message_federate helics_messagefederate_createmessagefederatefromfile (const char *fileName);
```

**Option 2**

```c 
helics_{action}[_{subject}] ( ... ) {
    ...
}
```

This option excludes the module name in favor of description action names on an optional subject.

e.g.

```c
helicsStatus helics_setfederateinfofederatename (helics_federate_info_t fi, const char *name);
helicsStatus helics_setfederateinfocorename (helics_federate_info_t fi, const char *corename);
helicsStatus helics_setfederateinfocoreinitstring (helics_federate_info_t fi, const char *coreInit);
```

This following function no longer requires a module name.

```c
helics_core helics_create_core (const char *type, const char *name, const char *initString);
```

There's no redundant naming, however autocomplete in IDEs may not be as helpful as in Option 1. This can be countered by using regex to search.

```
helics_message_federate helics_createmessagefederate (const helics_federate_info_t fi);
helics_message_federate helics_createmessagefederatefromfile (const char *fileName);
```

Option 2 can also be set up using underscore separators for every word.

```c
helicsStatus helics_set_federate_info_federate_name (helics_federate_info_t fi, const char *name);
helicsStatus helics_set_federate_info_core_name (helics_federate_info_t fi, const char *corename);
helicsStatus helics_set_federate_info_core_init_string (helics_federate_info_t fi, const char *coreInit);
```

**Comment by phlptp** [comment]
wouldn't the helics_core_*  be its own module.  There are a few functions we need to add for the core and broker yet and those would go in that "module"  so  helics_core_create(...

**Comment by kdheepak** [comment]
Okay, that makes sense, then that point can be discarded in the comment above. So the related question is are there other functions that wouldn't necessarily fall under a "module"?

**Comment by nightlark** [comment]
I prefer option 1, minus some redundant information -- instead of helics_messagefederate_createmessagefederate[fromfile], the method would be helics_messagefederate_create[fromfile]. Underscore separators looks like some names result in a lot of underscores, and makes the module name harder to recognize.

**Comment by abhyshr** [comment]
Sorry for being late in this conversation. Thanks for bringing this up, @kdheepak. It's great to have this information at this early stage of HELICS development. Here are my thoughts:

1. Is there a particular advantage to switching to using underscores than the existing CamelCase format? I use CamelCase and most scientific software I know, including PETSc and SunDials, use a CamelCase format for naming functions and objects. There is this paper http://www.cs.loyola.edu/~binkley/papers/icpc09-clouds.pdf that advocates using CamelCase but I'm sure there may be other papers having a differing view. The question is whether to switch to underscores instead of CamelCase. Having worked with both underscore and CamelCase format, I prefer CamelCase because it is easier to understand and interpret. But, I'm completely fine to use underscores if you all think it provides better value.

2. Regardless of whichever format is chosen, I think having a single format would promote uniformity used for both data types and function names. Currently, the function names use a mixed CamelCase for function names (e.g. helicsSetDefaultDouble) and underscores for data types (e.g. helics_time_t). 

3. I prefer function names starting the ObjectName rather than the prefix helics. I like the <Object><Action> or (object)_(action). I am not sure if having the prefix helics adds any specific value to the function name. In my opinion, it only makes the function names longer. Yes, one can argue that it makes it more clear that it is a HELICS function, but I don't think that is a strong argument. 

4. Common functions and datatypes that are used by ALL objects, e.g. helicsStatus (note that this should be either helics_status or HelicsStatus), could be prefixed with Helics. Other example is HelicsEnterXXXMode.  Functions for objects such as ValueFederate and others can start with its own object name e.g. ValueFedereateCreate instead of HelicsCreateValueFederate.

5. Constants should be all caps. HELICS has this currently.

6. In PETSc, we differentiate between C and C++ headers by having an extension .h and .hpp, respectively. So ValueFederate_c.h would be just ValueFederate.h. Note that CamelCase is not necessarily needed for filenames.

7. Maybe think of abbreviating some of the object names and their associated functions, e.g. instead of ValueFederate use ValueFed, instead of FederateInfo use FedInfo? Shorter function and data type names.

8. Rename HelicsEnterXXXMode to HelicsXXXBegin() or HelicsXXXInitiliaze, and a corresponding HelicsXXXClose() or HelicsXXXFinalize(). I am saying this because I find the name helicsEnterXXXModelFinalize() confusing.

**Comment by phlptp** [comment]
@abhyshr made me think a little bit of what I was basing the "not completely consistent" standard as it exists.  For the most part I just did the same as I did in the GridDyn C interface.  But that was based off the FMI API.  which used camelCase {namespace}{Action}  they didn't really have objects so in GridDyn I always did {namespace}{Object}{Action}  the namespace is always in lowercase,  along with a tendency to name simple or enumerated types with underscores.    Come to think of it Shri is right, with the exception of zmq most of the C libraries I have interacted with use camelCase,  so I am inclined to agree with Shri that we should use some form of that.

**Comment by kdheepak** [comment]
Thanks for the detailed reply @abhyshr. 

The [GNU Coding Standard](https://www.gnu.org/prep/standards/html_node/Names.html#Names) asks that people use underscores to separate words in names, so that it will be easier to navigate with Emacs. And, I think the main argument for underscores comes from this [CppCodingStandard](https://users.ece.cmu.edu/~eno/coding/CppCodingStandard.html#cnames) which states that using underscores for C functions clarifies that they are different from CPP. The [CPP Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl10-avoid-camelcase) also seems to recommend against camelCase. It seems that the only thing common across every style guide is that developers should ensure that they are internally consistent.

That said, I'm for using camelCase for all functions, C and CPP. I think separating the C functions from the CPP functions visually is appealing. However, we already have a `helics` prefix for all C functions, which should suffice. In addition, documentation and file layout will separate the C functions from the CPP functions. 

I do like the idea of having underscores for general naming. [Google's CPP style guide](https://google.github.io/styleguide/cppguide.html#Naming) recommends underscores for general naming, camelCase for functions and PascalCase for Classes. 

I also think the prefix `helics` is necessary for clean code. If there were another library with a same `set{Object}` function, there would be a conflict, would there not?. Using the `helics` prefix provides a namespace to ensure that no conflicts can occur. And coming from Python, in my experience I have found that it has made my life so much easier when I know where a function is coming from when I am reading a codebase developed by someone else. So I would say that quickly being able to identify which functions are coming from HELICS is definitely an advantage, at the small cost of being slightly verbose. It also would help in autocompletion when someone is working with HELICS. 

I agree with your other points. I'll be making these changes to a branch and requesting a review from everyone that comments on this thread. Feel free to add more thoughts and comments here.

**Comment by phlptp** [comment]
Lets write up a simple document with the proposed style guide before modifying any code, we can finish hashing out the document, then make the required changes over the next couple weeks and potentially encode some of them in a analyzer as well.

**Comment by kdheepak** [comment]
I will add a page to the documentation that describes coding style.

**Comment by abhyshr** [comment]
On Dec 14, 2017, at 8:14 PM, Dheepak Krishnamurthy <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the detailed reply @abhyshr<https://github.com/abhyshr>.

The GNU Coding Standard<https://www.gnu.org/prep/standards/html_node/Names.html#Names> asks that people use underscores to separate words in names, so that it will be easier to navigate with Emacs. And, I think the main argument for underscores comes from this CppCodingStandard<https://users.ece.cmu.edu/%7Eeno/coding/CppCodingStandard.html#cnames> which states that using underscores for C functions clarifies that they are different from CPP. The CPP Core Guidelines<https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl10-avoid-camelcase> also seems to recommend against camelCase. It seems that the only thing common across every style guide is that developers should ensure that they are internally consistent.

That said, I'm for using camelCase for all functions, C and CPP. I think separating the C functions from the CPP functions visually is appealing. However, we already have a helics prefix for all C functions, which should suffice. In addition, documentation and file layout will separate the C functions from the CPP functions

I do like the idea of having underscores for general naming. Google's CPP style guide<https://google.github.io/styleguide/cppguide.html#Naming> recommends underscores for general naming, camelCase for functions and PascalCase for Classes.

I'm fine with whichever format you guys decide. However, having a single format would be easy to remember for the user, in my opinion.

I also think the prefix helics is necessary for clean code. If there were another library with a same set{Object} function, there would be a conflict, would there not?.

Yes, but that's really really rare probability. I've only heard a couple of times of this issue happening with any of PETSc functions, which has been used for over twenty years now.

Using the helics prefix provides a namespace to ensure that no conflicts can occur. And coming from Python, in my experience I have found that it has made my life so much easier when I know where a function is coming from when I am reading a codebase developed by someone else. So I would say that quickly being able to identify which functions are coming from HELICS is definitely an advantage, at the small cost of being slightly verbose. It also would help in autocompletion when someone is working with HELICS.

That's a good point. I am not opposed to having a prefix, but I think it is redundant and only makes the function names longer. I agree with you on the auto-complete point. Speaking of autocomplete , do you guys recommend any auto-complete libraries for emacs? I use autocomplete from MELPA, but I've not figured how to have autocomplete the function prototypes from a third-party library like Helics. Any suggestions? Has anyone tried Cedet semantics or Irony?

I agree with your other points. I'll be making these changes to a branch and requesting a review from everyone that comments on this thread. Feel free to add more thoughts and comments here.

**Comment by abhyshr** [comment]
That's a very good proposition.

On Dec 14, 2017, at 10:47 PM, Philip Top <notifications@github.com<mailto:notifications@github.com>> wrote:


Lets write up a simple document with the proposed style guide before modifying any code, we can finish hashing out the document, then make the required changes over the next couple weeks and potentially encode some of them in a analyzer as well.

**Comment by kdheepak** [comment]
I've started putting together the style guide [here](https://GMLC-TDC.github.io/HELICS-src/style-guide.html).

**Comment by phlptp** [comment]
Coming from VisualStudio I use autocomplete frequently and having all the available functions from a single library show up when I type the library name is very useful.  the same goes for specific modules in the library to see what functions are available.  

as far as namespace collisions I am not that concerned about function name collisions for most functions, but if we don't include the name on the C function then the C++ wrapper will require a distinct name and that is something I would like to avoid.

**Comment by phlptp** [comment]
@abhyshr I am going to separate out comment 8 you made to its own issue since it is a little distinct from the nameing convention discussion

**Comment by jcfuller1** [comment]
Generally, I like the document -- I really don't have a strong opinion about what style is used, but rather one is used.

Should additional elements be added to this (or is that becoming too burdensome)?  Such as:
- When is it okay to use pointers? (or more importantly, when not to use them)
- When should variables be public v. private?
- Space, tabs, line lengths, conditional formatting, expressions, etc? (all these can be reformatted by an editor, but do we declare what we are using)?
- Defined commenting style or header blocks? (for later parsing)
(this list could go on)

Maybe instead we default back to established guidelines for specific languages (e.g., Cocoa Coding Guidelines)?

**Comment by phlptp** [comment]
Any code formatting issues are encapsulated in the .clang_format file if you want to discuss them it is open but we can encode those rules pretty easily.  

what is not captured in that file is the naming conventions, I think some can be encoded in a .clang_tidy file but that is a ways off yet.  

I think we can work out documentation standards in a later step, so I think we should get there but one step at a time.   as far as other coding guidelines I am hesitant to encode those to much at this stage would prefer we focus on the automated tools to catch potential issues.  

In any case I think this document that Dheepak has should clearly focus on naming conventions

**Comment by abhyshr** [comment]
The CamelCase format for function names in the style guide is incorrect. PascalCase and CamelCase are basically the same. The first letter in CamelCase is capitalized. The function name in the style guide should be `RegisterGlobalPublication` and not `registerGlobalPublication`. Thus, the function names and class (or struct) names would follow CamelCase. Any fields in it (including function pointers) will use small letters with underscores, if needed. Here are a few suggestions:

Structs and Classes: CamelCase format
Struct or class fields: lowercase with underscores if needed
```
typedef struct HelicsObject {
int some_int;
};

Function Names: CamelCase format
Order of arguments: Inputs first followed by the outputs. 
Return type: HelicsStatus -- I propose all public API functions return HelicsStatus so that we can use it for error checking. 
```
HelicsStatus HelicsRegisterGlobalPublication(InputType input, OutputType *output);
```

Constants: All CAPS
We could define it in a single constants.h file rather than have them dispersed in several headers. I would suggest not having constants declared via `const`. It makes difficult to track down what the value of the constant is and where it is being set.
```
#define HELICSCONSTANT <constant_value>;

Enumerations: CamelCase
Any of its fields: ALL CAPS since they are basically constant
```
typedef enum HelicsEnum{
 HELICS_OK;
 HELICS_ERR;
};
```
Also, I propose we use lowercase for filenames with underscores if needed. Using a .c and .h extension for C and .cpp and .hpp for C++. I don't think this is a high priority, but it is a simple way of differentiating between C and C++ code.

**Comment by phlptp** [comment]
In C++ it is much more preferable to use constexpr/const objects vs a #define to allow for type checking so defines should be avoided.  This is not possible in C.  

In generate in C++ I have always gone with the .h and .cpp file names matching the name of the class including capitalization.

in the C interface the helicsStatus or possibly renamed to helics_status would be indicative of errors.  Not all the functions can return errors,  nor do I have a clear idea how that would work for the object creation functions. 

```
int helicsCoreIsConnected (helics_core core)
```
returns 1 if a core is connected, if the core is invalid it obviously isn't connected.  There is no error possibility of an error condition hence returning a helics_status is misleading.  In the library at present if helicsStatus is returned there is the possibility of an error, if not there is no possibility of an error, and on the construction functions returning through a pointer would be very confusing as to memory management.  

```
helicsStatus helicsGetPublicationUnits (helics_publication pub, char *str, int maxlen);
```
there are many functions like this where the output is placed in a string.  The user manages memory of the string and must provide a valid memory and size.  In some ways maxlen is part of the output str, but it is used as an input variable.  It is not clear that switching the order of these makes it better as most functions like that take pointer then size vs the other way around.

**Comment by phlptp** [comment]
This is pretty much done in the C_unit_tests library now,  if anyone notices remaining issues add a new issue.  

two exceptions left in place were 
data_block
and data_view.  

These are classes, but they kind of fall in a gray area between matching the std:: interface and fundamental types and classes.  Any opinions on the matter?

**Comment by phlptp** [comment]
Please create a new issue for any remaining inconsistencies in the API naming
