### ISSUE TITLE
Default behavior for subscriptions

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#426]
What should the default behavior be for subscriptions.  
In the 2.0 alpha release I am removing the distinct function calls for required and optional subscriptions in favor of a single call, and some function to set and retrieve options for the interface handles.  One of the properties that can be set is a required/optional option.  

The subscription call is essentially a wrapper around a nameless namedInput, along with an addSourceTarget call.    So namedInputs like publications will not have a required flag set.  But the question is  should a subscription target be required by default(this can of course be changed)  But should the default behavior be to
1),  create an Error if the requested publication is not present in the federation
2).  be optional.  

I have gone back and forth on this so I don't have a clear answer so I am looking for other opinions?

**Comment by bpalmintier** [comment]
I think the default should be to raise an error, so that simple users know that no errors increases the odds the exchanges they expected actually happened.

Have a published value be optional globally could be an advanced option for folks, perhaps for very large federations, but even then it should be logged as a warning.

Perhaps, though, the best flexibility would be to have the federate be able flag individual subscriptions as optional, such that they would still get the checks for most uses and also have planned for when it is optional.

**Comment by phlptp** [comment]
Are you thinking like a flag at the federate level that can set the default value of whether targets are optional or required?
