### ISSUE TITLE
Should subscriptions have types?

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#428]
Right now we have type associated with publications,  with the new input interface there will also be a named type associated with it.  
The question is should subscriptions which are inputs with no names associated with them have a type in the function call.  Types were intended to be a way of specifying what the underlying raw data was.  The Application API specifies a number of well defined types that it knows about but arbitrary ones can be used for passing raw data.   So they are required for publications, and for inputs you want to be able to specify the type you are expecting.  But subscriptions have a different meaning in that a user should either know or not care and check what the data is when subscribing to a publication.  So on the uses that I have observed no one has actually used the type on a subscription for much meaning.  

So I am considering removing that field from the application API/ and C API calls for registering subscriptions.  
Does anyone have any thoughts on this?  

I may add a checkCompatibleType call for inputs to do a verification that the input types are compatible as well to take care of one use case for types.

**Comment by bpalmintier** [comment]
I actually think we should keep them, with the idea that a federate knows how it wants to get the data, but the sending federate might opt to change how it sends the data.

**Comment by phlptp** [comment]
I have played around with this for a while and I think the subscription call will not have a type argument.  
The reason is that most use cases I have seen won't use it,  they will use one of the default types which are all convertible anyway.  
And if a type is needed  a subscription is mostly a convenience wrapper around a nameless input (which can have a type) and an addSourceTarget call.  So in the rare case when a type is needed for a subscription it can be done just with two calls instead of one.

**Comment by phlptp** [comment]
I am somewhat reluctant to add the argument to the registerSubscription function.  That is meant to a be simplifying wrapper.  If you want to add types I would suggest just writing your own wrapper that takes a type, and calls registerInput and addTarget.     

also be aware that HELICS translates types where it can.  So a double on side can be converted to a string on the other.    So the types don't need to be an exact match for the data to transfer effectively.    

I suppose that is an idea that there might be a need for a flag specifying a strict type matching so double matches with a double only and issues an error otherwise.

**Comment by afisher1** [comment]
Well I find converting types dangerous. When I create a subscription in GridLAB-D I need to match the subscription type with the internal variable type. if the subscription type and the publication type don't match then we've configured the federation incorrectly in my opinion. 

On a related note. When I tried to  circumvent this issue by actually implementing inputs instead of subscriptions in federate configuration file I noticed that the api doesn't support specifiying targets in the configuration file. The constructors don't bother looking for a 'target' key and calling addTarget(). So I can't create a subscription with a type from the config file nor an input with a target. I would at least prefer to be able to do one or the other.

I know how to implement both features in the source code so I can do the work. I just need to know if the team wants either feature provided by the api.

**Comment by phlptp** [comment]
I thought that targets could be specified in the config file.  If that is not true, I will add that.

**Comment by Jacobhansens** [comment]
I am curious why we would not add the type (and any other functionality from input) to the subscription wrapper? Seems to me that all we have to add is one line in each of the configuration readers JSON and TOML for the type. Am I missing something?

I come at it from the user perspective. Currently we telling users that they can specify either a subscription (nameless input with target) or an input in the configuration files. If the user elects to do inputs it supports types, but a subscription do not? I find that very confusing as a user. I especially find it confusing as I am then asked to do a nameless input with a target (which is what a subscription is suppose to be). If we are not expanding the subscription wrapper I would highly question why we even keep it in the API and not just force everyone to use inputs in the first place. Half supporting it I think will cause many issues down the road with inconsistent federate design. Let me know what you think.

Lastly, I am in full support of a flag specifying a strict type matching so double matches with a double only and issues an error otherwise. I think this is important as most of the use case I have worked on will most likely not work properly if conversion is made

**Comment by Jacobhansens** [comment]
Also, it looks like neither subscriptions or inputs support setting the option that subscription/input are required and not optional. Can we add that?

**Comment by phlptp** [comment]
> Also, it looks like neither subscriptions or inputs support setting the option that subscription/input are required and not optional. Can we add that?

The options are coming in the flag_test branch and upcoming PR that I am working on, so they are coming,  one of the last ones I want to get working before beta.2  So hopefully by the end of the week.

**Comment by phlptp** [comment]
As far as types in subscriptions, My initial feeling was to remove the subscription notion entirely but after several conversations it was determined that would be disruptive when moving to the 2.0 branch from 1.X.  

As far as the registerSubscription in the API call I feel rather strongly that should be kept as simple as possible  (targetKey and units).

But if want the config to support other options in subscriptions such as a type that isn't a big deal to me.

**Comment by Jacobhansens** [comment]
> As far as types in subscriptions, My initial feeling was to remove the subscription notion entirely but after several conversations it was determined that would be disruptive when moving to the 2.0 branch from 1.X.
> 
> As far as the registerSubscription in the API call I feel rather strongly that should be kept as simple as possible (targetKey and units).
> 
> But if want the config to support other options in subscriptions such as a type that isn't a big deal to me.

Just so I understand. Are you suggesting to change the way the config registers the topic in the subscription section from `registerSubscription` to actually use the `registerInput` and by that, effectively supporting types (and other options) for both subscriptions and inputs. If yes, then I can get behind that. That would provide enough flexibility I think while also not changing the  `registerSubscription` call (even though I still personally question why we keep it in there when we clearly want people to use inputs).

**Comment by Jacobhansens** [comment]
> I am also curious why you think the conversions will cause issues. Many of the cases I have worked with it wouldn't work without conversions. Take for example the recorder, only works with strings. And there were a few programs that basically send all numbers as strings, so if you are strict you can't connect to those kinds of programs.

I see your point and I am not saying it will cause issues in all configuration. Some, like the one you describe it is absolutely needed. However, for the Co-Simulation I have been working on I am using complex values and from your table of conversion I see that potential loss of information can happen with this type (and others). That is why I think a flag that enables strict type matching might be useful to have. Another option would be to have a flag the user sets that will flag all conversions as a warning message. That way the user can easily identify the conversion and make a decision if they are appropriate.

**Comment by phlptp** [comment]
I think as far as the API call we should leave it as is for the moment and maybe in 2.2 release mark it as deprecated  them remove it in the next major release.  

For the config file then the only difference between inputs and subscriptions is subscriptions will be all local and all nameless.  Otherwise the options will be identical.

**Comment by Jacobhansens** [comment]
I can get behind that plan. If you want I am happy to provide a review of #536. That way I can make sure I capture how you made the change.

**Comment by Jacobhansens** [comment]
All my concerns were addressed by #536. I will close this one again.
