### ISSUE TITLE
Runtime errors with the C-API Function: helicsGetPublicationKey()

### ISSUE THREAD

**Issue by HimanshuJain17** [GMLC-TDC/HELICS-src#47]
@phlptp  I am attaching the `test-value-federate1.cpp` file that I am currently testing as part of the C-API testing task. As I discussed with you on Gitter, when `helicsRegisterPublication` is called without the `type` and `units` (which are specified as `""` in the call), `helicsGetPublicationKey` throws an exception.

 
[test-value-federate1.txt](https://github.com/GMLC-TDC/HELICS-src/files/1560915/test-value-federate1.txt)

**Comment by phlptp** [comment]
when you leave off the type, it routes to a generic publication, which just works with raw data through the core. the get PublicationKey function doesn't check that like it should and instead calls the Publication object which doesn't actually exist.

This will be fixed in the C_unit_tests branch later today

**Comment by HimanshuJain17** [comment]
Thanks @phlptp

**Comment by phlptp** [comment]
@HimanshuJain17 can you verify this is fixed when you get the chance, and if so close the issue

**Comment by HimanshuJain17** [comment]
@phlptp Will work on it today and close the issue if the problem is fixed.

**Comment by HimanshuJain17** [comment]
@phlptp The issue is fixed. The `value_federate_publication_registration` test passes without error. Closing the issue
