### ISSUE TITLE
Add macos build to Travis

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#8]
I think we should have a mac build in the travis scripts.  I regularly build on Windows and Linux, but mac is a little more challenging as I don't have access to any mac systems older than Sierra.  Having a build in Travis with a slightly older version using appleclang would test out a few bits of code we don't currently build against.

**Comment by nightlark** [comment]
The default is El Capitan (10.11) with Xcode 7.3.1, and the oldest Travis supports is Yosemite (10.10) with Xcode 6.4. I can try setting up builds on Yosemite first.

**Comment by phlptp** [comment]
I think either would be fine

**Comment by kdheepak** [comment]
I've added a Mac and Linux build in .travis.yml

The [Linux](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/294991525) builds are failing because cmake is now no longer the latest version, and this should be easy to fix. However the [Mac](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/294991522) builds are also failing. @phlptp @jeffdaily Can you take a look at this log to see if anything pops out?

**Comment by kdheepak** [comment]
See branch #13

**Comment by nightlark** [comment]
I'm trying to get travis building on an older version of macOS, but there are a different set of problems that occur.

**Comment by nightlark** [comment]
A travis config with macOS builds got merged into develop with PR #22.

**Comment by phlptp** [comment]
This will get merged to master when we next update master
